version: '2'
services:
  console:
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["10.2.5.52:9092"]
        connect:
          enabled: true
          clusters:
            - name: staging
              url: http://10.2.21.115:8002
    ports:
      - "8001:8080"